import PageContent from "@/Components/Layout/PageContent";
import { auth } from "@/Firebase/clientApp";
import { communityState } from "@/atoms/communityAtoms";
import { Inter } from "@next/font/google";
import Head from "next/head";
import { useEffect, useState } from "react";
import { useAuthState } from "react-firebase-hooks/auth";
import { useRecoilValue } from "recoil";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [user, loadingUser] = useAuthState(auth);
  const [loading, setloading] = useState(false);
  const communityStateValue = useRecoilValue(communityState);

  const buildUserHomeField = () => {};

  const buildNoUserHomeField = () => {
    setloading(true);
    try {
    } catch (error) {
      console.log("BuildNoUserHomeField");
    }
    setloading(false);
  };

  const getUserPostVotes = () => {};

  useEffect(() => {
    if (!user && !loadingUser) buildNoUserHomeField();
  }, [user, loadingUser]);

  return (
    <>
      <Head>
        <title>Sag-Reddit</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        style={{
          minHeight: "100vh",
        }}
      >
        <PageContent>
          <>Postfeed</>
          <>Recomendation</>
        </PageContent>
      </main>
    </>
  );
}
