import PageContent from "@/Components/Layout/PageContent";
import { auth } from "@/Firebase/clientApp";
import { Inter } from "@next/font/google";
import Head from "next/head";
import { useAuthState } from "react-firebase-hooks/auth";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [user] = useAuthState(auth);

  const buildUserHomeField = () => {};

  const buildNoUserHomeField = () => {};

  const getUserPostVotes = () => {};

  return (
    <>
      <Head>
        <title>Sag-Reddit</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        style={{
          minHeight: "100vh",
        }}
      >
        <PageContent>
          <>Postfeed</>
          <>Recomendation</>
        </PageContent>
      </main>
    </>
  );
}
